### ISSUE TITLE
Am I doing this right?

### ISSUE THREAD

**Issue by domchristie** [seanpdoyle/attributes_and_token_lists#21]
I'm beginning to experiment with this, mainly for form inputs, and have implemented the following:

```rb
module UiHelper
  def ui
    @ui ||= Ui.new(self)
  end

  class Ui
    delegate_missing_to :@view_context

    def initialize(view_context)
      @view_context = view_context
    end

    def text_input
      tag.attributes class: "block w-full bg-grey-200 border-transparent focus:bg-white"
    end
  end
end
```

```erb
<%= form_with … |form| %>
  <%= form.label :query, "Search" %>
  <%= form.search_field :query, ui.text_input.with_attributes(value: params[:query], class: "py-1 pr-1 pl-8") %>
<% end %>
```

Am I along the right lines with this approach? Thanks!

**Comment by seanpdoyle** [comment]
I think so!

I'm in the process of exploring a built-in way of declaring clusters of attributes and classes without having to declare the builder (the `Ui` class in your example code). It's coming out to something like:

```ruby
  AttributesAndTokenLists.define :atl do
    define :button, tag_name: :button, class: "text-white p-4 focus:outline-none focus:ring" do
      define :primary, class: "bg-green-500"
      define :secondary, class: "bg-blue-500"
      define :tertiary, class: "bg-black"
    end
  end

require "test_helper"

class AttributesBuilderTest < ActionDispatch::IntegrationTest
  test "reads configuration from app/views/initializers" do
    post examples_path, params: {template: <<~ERB}
      <%= atl.tag.button "Unstyled" %>
      <%= atl.button.tag "Base" %>
      <%= atl.button.primary.tag "Primary" %>
      <%= atl.button.secondary.tag "Secondary" %>
      <%= atl.button.tertiary.tag "Tertiary" %>
      <%= atl.button.primary.tag.a "Primary", href: "#" %>
      <%= atl.button.primary.link_to "Primary", "#" %>
    ERB

    assert_button "Unstyled", class: []
    assert_button "Base", class: %w[text-white p-4 focus:outline-none focus:ring]
    assert_button "Primary", class: %w[text-white p-4 focus:outline-none focus:ring bg-green-500]
    assert_button "Secondary", class: %w[text-white p-4 focus:outline-none focus:ring bg-blue-500]
    assert_button "Tertiary", class: %w[text-white p-4 focus:outline-none focus:ring bg-black]
    assert_link "Primary", href: "#", class: %w[text-white p-4 focus:outline-none focus:ring bg-green-500], count: 2
  end
end
```

**Comment by domchristie** [comment]
Nice! I'm finding that my buttons and inputs just need size and color customisation, so I was considering something like `ui.text_input(size: :sm).with_attributes(…)`, with `ui.text_input` returning the defaults.

**Comment by domchristie** [comment]
I'm curious about this approach with `link_to` view helpers:

```erb
<%= atl.button.primary.link_to "Primary", "#" %>
```

Can I apply this pattern with a Rails form builder? If so what would it look like? (My initial brief experiments haven't quite worked.)

**Comment by domchristie** [comment]
> I'm in the process of exploring a built-in way of declaring clusters of attributes and classes without having to declare the builder

This looks like a reasonable approach: https://stitches.dev/docs/variants In Ruby, this'd be 🔥

**Comment by seanpdoyle** [comment]
@domchristie your suggestion has rattled around in my head for 4 or 5 months, and finally came to fruition: https://github.com/seanpdoyle/styled_helpers

**Comment by domchristie** [comment]
@seanpdoyle amazing! I'll check it out…

**Comment by domchristie** [comment]
I've also just come across: https://github.com/avo-hq/class_variants

**Comment by domchristie** [comment]
> I've also just come across: https://github.com/avo-hq/class_variants

Although styled_helpers looks preferable as it can handle multiple attribute types (rather than just classes)
